techmatters/terraso-client-shared

src/account/accountService.ts, src/account/accountSlice.ts, src/account/auth.ts, src/config.ts, src/terrasoApi/api.ts, src/tests/config.ts
The mobile client needs to use Promises to fetch and store tokens, while the web client uses a synchronous Cookie API. In order to support both I changed the function type to return a Promise. It created a bit of difficulty with the Redux store; the initial state can't be set automatically because the getToken function is now async. It will mean that the client code will have to call the `getInitialToken` action on startup. We can maybe take another look at
this later.
=> feat: Allow using promises for token config

package-lock.json, package.json, src/account/accountSlice.ts, src/config.ts, src/project/projectFragments.ts, src/project/projectService.ts, src/project/projectSlice.ts, src/site/siteFragments.ts, src/site/siteService.ts, src/site/siteSlice.ts, src/store/store.ts, src/terrasoApi/utils.ts
Adds a redux slice and API service for projects and sites. Currently still in draft, waiting for backend PR https://github.com/techmatters/terraso-backend/pull/634 to land and to update commit tag.
Closes #17
Closes #18
=> feat: add project/site service/slice

package-lock.json, package.json
Remove plausible-tracker node module. It's not used by `client-shared`.
=> chore: remove plausible-tracker node module

.github/workflows/build.yml
It fails every time and we merge anyway. Can be restored as part of completing #2.
=> chore: temporarily disable coverage check

package-lock.json, package.json
chore: move @ianvs/prettier-plugin-sort-imports to devDependencies
Follow on to #41.
=> chore: move @ianvs/prettier-plugin-sort-imports to devDependencies

.github/workflows/build.yml
Don't run update-web and update-mobile on PR. These steps should only run on pushing to main.
=> fix: don't run update-web and update-mobile on PR

.github/workflows/update-shared.yml
remove extra `npm install` command from GitHub Actions workflow for updating web client.
Use GitHub action for committing updated module.
=> fix: remove extra npm install command abd GitHub action for commits

.github/workflows/update-shared.yml
Update shared client without causing extra changes.
running `npm install` without `--no-package-lock` causes extra diffs in the package-lock.json and causes `npx graphql-code-generator to fail`.
=> fix: update shared client without causing extra changes

package-lock.json, src/project/projectService.ts, src/site/siteService.ts
The project service was updating user's sites with unprocessed `SiteNode`s from the graphql response. I think this error would've been caught by the compiler if the TypeScript type for `Site` had `projectId: string | null` and `ownerId: string | null` instead of `projectId?: string`, but then we would be forced to manually specify null everywhere when creating new sites. which isn't that common so might be a good trade-off. anyway i will file a separate issue for that, for now this is just the bug fix
=> fix: collapse site fields in project service

package-lock.json, package.json, src/project/projectFragments.ts, src/project/projectService.ts, src/project/projectSlice.ts
Updates the `Project` datatype to contain Memberships. Uses the Membership List object from the backend, but does not keep any reference to the membership list; the mutations to update Membership info now pass through the project.
I realize now that I still haven't implemented the endpoints to add members to projects, remove them, etc. This mostly has not been implemented in the mobile client, so that can be implemented when the time comes.
Should be merged after [backend PR](https://github.com/techmatters/terraso-backend/pull/793)
Fixes #....
=> feat: Use Membership List in project

package-lock.json, package.json, src/account/accountService.ts
This will make it so the email match in the projects field does not care about if the user uses upper case or not.
Fixes #....
=> fix: Use case-insensitive match for user existence email query

src/project/projectService.ts, src/project/projectSlice.ts
This PR should add a way to update the user's role on the backend, and in the redux store.
Fixes #....
=> feat: Add thunk for updating user role in project

src/project/projectService.ts, src/project/projectSlice.ts
This PR adds an operation to delete a user membership from a project on the backend, as well as update the redux state accordingly.
Fixes #....
=> feat: Add thunk to delete user from project

src/soilId/soilIdSlice.ts
Adding a loading state to the call that's populating the user's Sites and Projects data, so we can show loading indicators in the mobile app.
https://github.com/techmatters/terraso-mobile-client/issues/289
=> chore: add loading state

package-lock.json, package.json, src/selectors.test.ts, src/selectors.ts, src/site/siteService.ts, src/site/siteSlice.ts
I completely overlooked that unaffiliated sites, that is sites that are not a part of any project, must be included in the transfer site screen. This change just updates the relevant selector to include unaffiliated sites.
Related to https://github.com/techmatters/terraso-mobile-client/issues/145
=> feat: site transfer mutation

src/site/siteSlice.ts
Project update reducer needs to delete the site from the project slice on update, because this is the way that we're using to update the project slice sites for the moment.
Needed for https://github.com/techmatters/terraso-mobile-client/issues/431
=> fix: Delete sites from project slice on update

package-lock.json, package.json, src/project/projectFragments.ts, src/project/projectSlice.ts, src/selectors.test.ts
Bumps the backend version and updates the Project type to include measurement units. Relies on https://github.com/techmatters/terraso-backend/pull/927.
Related to https://github.com/techmatters/terraso-mobile-client/issues/253
=> feat: Allow editing project measurement units setting

src/selectors.test.ts, src/selectors.ts
We need to associate sites to user roles. The user role is selected as the user's role in the project to which the site belongs (undefined if the site does not belong to a project).
Part of work for https://github.com/techmatters/terraso-mobile-client/issues/42
=> feat: Add new selectors site filter

package-lock.json, package.json, src/project/projectFragments.ts, src/project/projectService.ts, src/project/projectSlice.ts, src/selectors.test.ts, src/site/siteFragments.ts, src/site/siteService.ts, src/site/siteSlice.ts
Adding Site Notes slice and service.
Fixes #113
=> feat: add site notes slice/service

src/selectors.test.ts, src/selectors.ts
- Needed to export one of the selectors that I was already using to map user role to project
- Realized in this process, re-reading the redux docs, that the selector was not defined properly, so had to refactor it a bit. The problem was that an intermediary selector was essentially creating a new object, which is not the way the intermediary selector are supposed to work. I separated out the function work and used it in the final selector.
- Changed the tests to adapt to the fact that the refactored selectors use the current user ID, instead of having to provide it explicitly.
Related to https://github.com/techmatters/terraso-mobile-client/issues/143
=> feat: select project by role

src/selectors.test.ts, src/selectors.ts
Adds a selector that will return a user's role to a site. It is unaffiliated, it will just return "owner" or null. Otherwise it will return the project role or null.
Fixes #....
=> feat: Selector for user role based on site

src/soilId/soilIdSlice.ts
Adds reducers that update the soil ID state automatically when a user presses a switch on the soil tab. If the request fails, it rolls back the data and changes the store status to "error".
This implementation is very much a first attempt. The fact that the soil ID update updates the whole soil ID object, and the fact that soil IDs are a list rather than a hash set, make the reverse code a bit hacky. Hopefully in the future we can look into some libraries that will make this sort of operation easier.
Fixes #....
=> feat: site soil async

package-lock.json, package.json, src/project/projectFragments.ts, src/project/projectService.ts, src/project/projectSlice.ts, src/soilId/soilIdSlice.ts
I made this to make sure that projects have soil settings - a bug was happening when a new project was created. However, I'm not really sure how this works with the already existing soilID fetch that already grabs settings - it seems like the work will be doubled a bit with this change.
BEFORE MERGING: Bump backend version when [backend PR](https://github.com/techmatters/terraso-backend/pull/1062) is merged
Fixes #....
=> fix: Read project soil settings from projects

package-lock.json, src/constants.ts, src/selectors.ts
If the user selects the LandPKS or NRCS presets, the project intervals are not stored in the backend but generated on the frontend. This PR introduces a selector that can be used to retrieve project settings from the redux store, and populate the correct project depth intervals according to the preset selected.
=> feat: Generate project intervals on frontend

package-lock.json, package.json, src/constants.ts, src/selectors.test.ts, src/selectors.ts, src/soilId/soilIdFragments.ts, src/soilId/soilIdSlice.ts, src/soilId/soilIdTypes.ts, src/utils.ts
The central part of this PR provides a selector that generates the correct soil pit intervals for a given site. It determines based on the redux store which soil pit intervals need to generated, and whether any of these soil pit intervals should be matched to existing soil pit interval data saved in the database. It also wraps this information in a type `AggregatedInterval`, which can be used to determine if the underlying interval also supports updating its bounds -- intervals generated by a project preset do not support this.
Fixes #....
=> feat: Support generating soil depth intervals on the frontend

src/selectors.ts
Site soil data preset default is null, not undefined - this changes it so we just check the bool value of the field
=> fix: Handle case where depth interval preset is null

src/selectors.ts
Restricts transferred sites in projects to where user is manager.
Fixes https://github.com/techmatters/terraso-mobile-client/issues/565 (but mobile client will need to be updated to use this version!)
=> fix: Restrict site transfer sites to projects where user is manager

src/soilId/soilIdTypes.ts
Just makes the ordering of the hues in the enum match that of the actual munsell color system. Needed for https://github.com/techmatters/terraso-mobile-client/pull/882
=> fix: hue ordering

src/project/projectSlice.ts, src/soilId/soilIdSlice.ts, src/store/utils.ts, src/utils.ts
Cyclic dependency issue with mutually referential redux slices. Resolved by changing some load time constants to callbacks that return the same constant. Untangling the cyclic dependency would be much higher effort.
https://github.com/techmatters/terraso-mobile-client/issues/884 will be resolved once this gets downstream.
=> fix: dispatch map

package-lock.json, package.json, src/project/projectFragments.ts, src/project/projectSlice.ts, src/selectors.test.ts, src/selectors.ts, src/soilId/soilIdTypes.ts
Makes available a few more types/enums for more convenient/consistent client usage.
Needed for https://github.com/techmatters/terraso-mobile-client/pull/959
=> feat: define more types and enums

package-lock.json, package.json, src/project/projectFragments.ts, src/project/projectSlice.ts, src/selectors.test.ts, src/soilId/soilIdFragments.ts, src/soilId/soilIdTypes.ts
Needed for https://github.com/techmatters/terraso-mobile-client/pull/979
=> fix: move measurement units to right model (d'oh!)

src/collaboration/membershipsFragments.ts, src/collaboration/membershipsUtils.ts
Rename MembershipsInfo to MembershipInfo, membershipsSample to memberships.
Fixes #216.
Supports https://github.com/techmatters/terraso-web-client/pull/1726
=> fix: rename MembershipsInfo to MembershipInfo, membershipsSample to memberships

package-lock.json, package.json, src/selectors.test.ts, src/site/siteFragments.ts, src/site/siteSlice.ts
Add elevation to shared client
Backend: https://github.com/techmatters/terraso-backend/pull/1286
=> feat: add elevation to shared client

package-lock.json, package.json
Downgrades react to a version compatible with the mobile client, which is stuck on version 18.2.0 because that's what react native has pinned.
=> fix: downgrade react for now

package-lock.json, package.json, src/soilId/soilIdFunctions.ts, src/soilId/soilIdSelectors.ts, src/soilId/soilIdService.ts, src/soilId/soilIdSlice.ts, src/soilId/soilIdTypes.ts, src/utils.ts
(Creating from Ruxandra's work)
- Allow fetching soil matches from the Soil ID API with inputs from actual site data or location coordinates supplied by the app
- Cache most recent soil ID results for a site in Redux store
- Also track the loading state status
Implements [#653](https://github.com/techmatters/terraso-product/issues/653)
Look at the soil ID info screen for a given soil (need the corresponding mobile-client work)
=> feat: Enable calling the Soil ID API with input from frontend

src/account/accountSlice.ts
After adding this SimpleUserInfo type to client-shared, I found the UserFields type in mobile-client, which is basically what I wanted in the first place. It's the same exact shape, so I want to remove the SimpleUserInfo type I added here.
As part of mobile-client [#1447](https://github.com/techmatters/terraso-mobile-client/issues/1447)
=> refactor: Remove unnecessary type

src/soilId/soilIdFunctions.test.tsx, src/soilId/soilIdFunctions.ts, src/soilId/soilIdHooks.ts, src/soilId/soilIdSelectors.ts, src/soilId/soilIdService.ts, src/soilId/soilIdSlice.ts, src/soilId/soilIdTypes.ts
Fix issues caused by soil ID loading by replacing the one-off loading system with a data cache. Soil ID slice can now hold arbitrarily-many soil ID match sets, each with their own status. Refactor some nearby code for readability.
#1647
See corresponding PR for mobile client.
=> fix: soil id data caching

src/soilId/soilIdHooks.ts, src/soilId/soilIdTypes.ts
Add `SoilIdData` type here so we can move it from mobile-client to client-shared.
This is follow-on refactoring to PR https://github.com/techmatters/terraso-mobile-client/pull/1688 
Related to https://github.com/techmatters/terraso-product/issues/895
=> refactor: Move SoilIdData type to client-shared (part 1)

src/selectors.ts
Rewrite `selectDepthDependentData` to use `createSelector` rather than chaining selectors inline. The `selectDepthDependentData` selector was causing a warning because of its internal use of `selectSoilData`. Redux recommends using the `createSelector` wrapper when chaining selectors together to avoid unnecessary re-renders. 
Fixes #1322
Open the application in developer mode and observe that the warning no longer spews to the console on the home screen or site screens.
=> fix: use createSelector to avoid redux selector warning

package-lock.json, package.json, src/constants.ts, src/selectors.test.ts, src/selectors.ts, src/soilId/soilIdTypes.ts
For depth presets:
- remove LandPKS
- add BLM monitoring standard
- make NRCS the default
- update tests
Client-shared part to address [#1541](https://github.com/techmatters/terraso-mobile-client/issues/1541)
=> feat: Update depth presets for Capri

src/account/accountSlice.ts, src/project/projectService.ts, src/site/siteService.ts, src/store/utils.ts
a miscellany of small changes related to [the global redux actions PR](https://github.com/techmatters/terraso-mobile-client/pull/2301) on the mobile client
Related to https://github.com/techmatters/terraso-mobile-client/pull/2301. Hold off on merging until https://github.com/techmatters/terraso-mobile-client/pull/2301 is ready.
=> refactor: companion PR for mobile client global redux actions PR

package-lock.json, package.json, src/soilId/soilDataFragments.ts, src/soilId/soilDataService.ts, src/soilId/soilIdFragments.ts
Shouldn't be merged until [associated backend PR](https://github.com/techmatters/terraso-backend/pull/1472) is merged.
@tm-ruxandra wasn't sure what data you wanted exposed in the response, right now it just sends back all the soil data for each site queried, but if you aren't going to use that data at all we can omit it to save the bandwidth
=> feat: expose pushSoilData endpoint

src/account/accountSlice.ts
This is so that when we get a user from the backend, we can add it to the redux state's cache of users.
This will allow us to pass a userId to the AddUserToProjectRoleScreen instead of the User object.
Which will allow the screen to detect if the user has been deleted from the system when a pull occurs.
Part 1 to address #2289
=> refactor: Add account slice action to add to cache of users

src/account/accountService.ts, src/account/accountSlice.ts
- Turn checkUserInProject into an asyncThunk
- When it is fulfilled, add the returned user to the cache of users
- Remove the action I recently added, since it is no longer needed
- Note tech debt that users' preferences probably shouldn't be included in the cache of users
Related to https://github.com/techmatters/terraso-mobile-client/issues/2289
=> refactor: When checkUserInProject returns a user, add them to accountSlice's cached users

package-lock.json, package.json, src/soilId/soilDataFragments.ts, src/soilId/soilDataService.ts, src/soilId/soilIdTypes.ts, src/soilId/soilMetadataService.ts
Add the ability to store metadata about soil data for sites in a new "site metadata" model. Expose a mutation for metadata, and include it in the queryable edges for sites.
[#2506](https://github.com/techmatters/terraso-mobile-client/issues/2506)
Verify other functionality through UI ticket.
=> feat: select soil

package-lock.json, package.json
I'd forgotten to run `npm install` after updating the backend version commit hash in package.json in [PR 1328](https://github.com/techmatters/terraso-client-shared/pull/1328). So do that.
Required for https://github.com/techmatters/terraso-backend/issues/1618
=> chore: update package-lock after package.json

package-lock.json, package.json
One more change here -- needed to run `npm update terraso-backend` to update the commit hash in the `package-lock.json` dependency tree
Required for https://github.com/techmatters/terraso-backend/issues/1618
Follow-on to PR https://github.com/techmatters/terraso-mobile-client/pull/2939
=> fix: Update backend dependency in package-lock.json correctly

package-lock.json, package.json
mobile-client has uuid v 10.0.0 and can't be updated until we fix a jest problem
This keeps the two in sync so we can build mobile-client with current version of shared client.
Test failure: https://github.com/techmatters/terraso-mobile-client/actions/runs/15005443651/job/42162785107?pr=2939
Potential solution at https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149
=> fix: Revert uuid back to 10.0.0

package-lock.json, package.json
Revert "fix: Revert uuid back to 10.0.0"
This reverts commit 2ab8c9db59111f60c6b83b01ee3968c2234a1852.
- The github workflows passed when updating mobile-client to uuid 11.1.0 alongside this change to client-shared. See https://github.com/techmatters/terraso-mobile-client/pull/2939/files
Uncertainties:
- I'm not entirely sure what was causing the failure
- I didn't check if using client-shared with the updated uuid 11 would cause issues on web-client though.
Tangentially related to https://github.com/techmatters/terraso-backend/issues/1618 in that we are just trying to bump mobile-client's dependency on client-shared, and were running into issues with the uuid version 
Mobile-client workflow steps pass when using this and updating uuid to 11
=> fix: Use uuid 11.1.0 again

package-lock.json, package.json, src/soilId/soilIdFragments.ts, src/soilId/soilIdService.ts
Make updates to client-shared that are required for global 
- Update backend dependency to latest commit
- Remove references to `locationBasedSoilMatches`
- Add `dataRegion` to `dataBasedSoilMatches`
FYI `management` will be handled in the client, so not adding it to the fragment
Required to address https://github.com/techmatters/terraso-mobile-client/issues/2670, https://github.com/techmatters/terraso-mobile-client/issues/2776, https://github.com/techmatters/terraso-mobile-client/issues/2777, https://github.com/techmatters/terraso-mobile-client/issues/2778, https://github.com/techmatters/terraso-mobile-client/issues/2847, https://github.com/techmatters/terraso-mobile-client/issues/2927
=> feat: Updates to enable global soil id functionality

package-lock.json, package.json, src/soilId/soilIdFragments.ts, src/soilId/soilIdService.ts, src/soilId/soilIdTypes.ts
To fix the issue where the new backend is incompatible with both 1.2 and 1.3 clients simultaneously (details [in slack here](https://tech-matters.slack.com/archives/C0376RCCXD2/p1752170651976809))
=> fix: Update backend to version with 1.2 and 1.3 endpoints
