- package-lock.json
- package.json
- src/account/accountService.ts
- src/account/accountSlice.ts
- src/account/auth.ts
- src/config.ts
- src/memberships/membershipsService.ts
- src/memberships/membershipsSlice.ts
- src/memberships/membershipsUtils.ts
- src/monitoring/logger.ts
- src/project/projectService.ts
- src/project/projectSlice.ts
- src/site/siteService.ts
- src/site/siteSlice.ts
- src/store/utils.test.tsx
- src/store/utils.ts
- src/terrasoApi/api.test.ts
- src/terrasoApi/api.ts
- src/tests/utils.tsx
> chore: update prettier

- package.json
Separate out `lint-js` and `format-js` to match web client and mobile client.
> fix: add format-js command to package.json

- src/store/store.ts
> fix: wrong import for project slice

- package-lock.json
- package.json
- src/project/projectFragments.ts
- src/project/projectSlice.ts
Changed the project description field.
> chore: Update backend

- package-lock.json
- package.json
> chore: Increased backend version

- package-lock.json
- package.json
- src/project/projectFragments.ts
- src/project/projectService.ts
- src/project/projectSlice.ts
- src/terrasoApi/utils.ts
It's likely that we will need to add some more details for later screens, but I wanted to get a start on the ones we need for the project display list.
I also added an utility function for unfolding GraphQL projects.
> feat: Add needed fields to projects.

- src/terrasoApi/api.test.ts
- src/terrasoApi/api.ts
- Omitted non serializable query from error message
> fix: Handle api errors

- .prettierrc
- package-lock.json
- package.json
- src/store/store.ts
- src/store/utils.test.tsx
- src/terrasoApi/api.test.ts
- src/tests/utils.tsx
Fixed import order prettier plugin
> fix: Fixed import order prettier plugin

- package-lock.json
- package.json
- src/site/siteFragments.ts
- src/site/siteSlice.ts
Adds site privacy field to redux slice and graphql query.
> feat: add site privacy field

- .github/workflows/build.yml
- .github/workflows/update-shared.yml
Update web client staging whenever a new shard client is released.
> chore: add action to update web-client staging with newest commit hash

- .github/workflows/update-shared.yml
Use GitHub action to commit changes instead of manually running git commands.
> fix: use GitHub action to commit changes

- package-lock.json
- package.json
- src/project/projectFragments.ts
- src/project/projectService.ts
- src/project/projectSlice.ts
Add archive project service and archive project slice
> feat: add archive projects to project service/slice

- package-lock.json
- package.json
- src/collaboration/membershipsFragments.ts
- src/collaboration/membershipsUtils.ts
- Added changes to support collaboration membership list
https://github.com/techmatters/terraso-web-client/issues/1037
https://github.com/techmatters/terraso-product/issues/336
> feat: Membership list

- package-lock.json
- package.json
> chore: Upgrade backend version

- package-lock.json
- package.json
- src/account/accountSlice.ts
- src/project/projectService.ts
- src/project/projectSlice.ts
This just adds a mutation to add a user to a project.
Fixes #....
> feat: Add GraphQL mutation to add user to project

- src/account/accountService.ts
This PR adds a method to check if 1) a user exists and 2) if they belong to a given project or not
Fixes #....
> feat: Add API call to check if user exists and is in project

- package-lock.json
- package.json
- src/account/accountService.ts
- src/account/accountSlice.ts
- src/project/projectFragments.ts
- src/project/projectService.ts
- src/project/projectSlice.ts
- src/site/siteService.ts
- src/site/siteSlice.ts
- src/soilId/soilIdFragments.ts
- src/soilId/soilIdService.ts
- src/soilId/soilIdSlice.ts
- src/store/store.ts
- src/store/utils.ts
- src/terrasoApi/utils.ts
- src/utils.ts
Creates a soil ID redux slice and service exposing all of the new soil ID related endpoints created in techmatters/terraso-backend#843 and techmatters/terraso-backend#819
Fixes #10
Fixes #11 
Fixes #85
> feat: soil ID slice/service

- package-lock.json
- package.json
- src/soilId/soilIdFragments.ts
Adds the 9 additional fields to the soilData fragment.
Fixes #111
> feat: add additional fields to soilData fragment

- package-lock.json
- package.json
- Link landscapes directly to shared files, links and visualizations
- https://github.com/techmatters/terraso-web-client/issues/1228
- https://github.com/techmatters/terraso-web-client/pull/1229
- https://github.com/techmatters/terraso-backend/pull/904
> refactor: Link landscapes directly to shared files, links and visualizations

- src/soilId/soilIdSlice.ts
Replacing the fulfilled state that I removed by mistake yesterday.
> fix: add fulfilled state

- src/account/accountSlice.ts
* add setCurrentUser function. allow for logout
* remove unused setUser function.
> fix: add setCurrentUser function

- package-lock.json
- package.json
- Backend version update
- https://github.com/techmatters/terraso-web-client/issues/1038
- https://github.com/techmatters/terraso-backend/pull/917
- https://github.com/techmatters/terraso-web-client/pull/1248
> feat: Visualization (data map) GIS formats support

- src/utils.ts
Moves isValidLatitude and isValidLongitude to client-shared for use in mobile-client.
> Feat: move lat/lon check to shared-client

- src/utils.ts
Add normalizeText to client-shared.
> feat: Add normalizeText to client-shared

- Makefile
- README.md
- package.json
- scripts/commit-msg.sample
- scripts/pre-commit.sample
Add git hooks to lint on commit. Match what is done on backend.
> chore: add git hooks to lint on commit

- src/selectors.ts
Just lets the type script compiler know what type we want for this selector.
Fixes #....
> fix: Fix typing for site user role selector

- package-lock.json
- package.json
- src/selectors.ts
- src/soilId/soilIdSlice.ts
- src/soilId/soilIdTypes.ts
- src/utils.ts
Adds some new selectors, some types related to soil texture, and a bit of code re-org. No breaking changes.
Needed for https://github.com/techmatters/terraso-mobile-client/pull/780.
Depends on https://github.com/techmatters/terraso-backend/pull/1123.
> feat: clay percent and texture changes

- src/account/accountService.ts
- src/account/accountSlice.ts
- src/account/auth.ts
- src/collaboration/membershipsUtils.ts
- src/config.ts
- src/constants.ts
- src/monitoring/logger.ts
- src/notifications/notificationsSlice.ts
- src/selectors.test.ts
- src/selectors.ts
- src/store/store.ts
- src/store/utils.test.tsx
- src/store/utils.ts
- src/terrasoApi/api.test.ts
- src/terrasoApi/api.ts
- src/tests/config.ts
- src/tests/setup.ts
- src/tests/utils.tsx
- src/utils.ts
Add copyright notices to more files. Ensure space is present after copyright block.
> docs: add copyright notices + fix spacing

- package-lock.json
- package.json
- src/soilId/soilIdFragments.ts
- src/soilId/soilIdTypes.ts
- src/store/store.ts
Adds some fields from backend, exposes some enums in TS friendly format. Needs to be merged after techmatters/terraso-backend#1149 so we can update to the right client shared version on that repo's main branch.
Needed for techmatters/terraso-mobile-client#849 and techmatters/terraso-mobile-client#850
> feat: add some fields (color, clay, cracking)

- package-lock.json
- package.json
- Shareable resource file for Landscapes and groups
- https://github.com/techmatters/terraso-web-client/issues/1322
> feat: Shareable file resource

- src/selectors.ts
- src/soilId/soilIdSlice.ts
Adds a selector for soil data which provides a default value.
Needed for https://github.com/techmatters/terraso-mobile-client/pull/887
> feat: soil data selector

- .eslintrc
- package-lock.json
- package.json
- src/constants.ts
- src/selectors.test.ts
- src/selectors.ts
- src/soilId/soilIdSlice.ts
- src/tests/utils.tsx
- src/utils.ts
Simplifies and correctifies the redux selectors related to depth intervals.
Related to https://github.com/techmatters/terraso-mobile-client/issues/502, needs https://github.com/techmatters/terraso-backend/pull/1188
> fix: depth interval selector overhaul

- package-lock.json
- package.json
Prep work for CJS -> ESM change.
> chore: add engines section to package.json

- src/selectors.ts
Code style fix. Remove unnecessary else block.
> fix: remove unnecessary else block

- package-lock.json
- package.json
- src/soilId/soilIdFragments.ts
- src/soilId/soilIdTypes.ts
Associated changes for https://github.com/techmatters/terraso-backend/pull/1198
Related to https://github.com/techmatters/terraso-mobile-client/issues/129
Needs https://github.com/techmatters/terraso-backend/pull/1198
> feat: change soil color data format

- .github/workflows/build.yml
These jobs fail every time so the main branch is just a bunch of red `x`s and we won't notice if there's an actual problem.
> ci: disable jobs that always fail

- package-lock.json
- package.json
update @babel/preset-env@7.24.4 @babel/preset-typescript@7.24.1.
> build: update @babel/preset-env@7.24.4 @babel/preset-typescript@7.24.1

- package-lock.json
- package.json
> build: update typescript to 5.4.5

- package-lock.json
- package.json
update @ianvs/prettier-plugin-sort-imports to 4.2.1.
> build: update @ianvs/prettier-plugin-sort-imports to 4.2.1

- package-lock.json
- package.json
Update @types/lodash to 4.17.0.
> build: update @types/lodash to 4.17.0

- package-lock.json
- package.json
update eslint-plugin-react to 7.34.1.
> build: update eslint-plugin-react to 7.34.1

- package-lock.json
- package.json
update @testing-library/react to 15.0.0.
> build: update @testing-library/react to 15.0.0

- src/selectors.ts
- src/soilId/soilIdTypes.ts
Just adding some type aliases/enums.
Needed for https://github.com/techmatters/terraso-mobile-client/pull/1065
> feat: use the actual set of possible color values from the soil book

- src/account/accountSlice.ts
To support work for[ #1447](https://github.com/techmatters/terraso-mobile-client/issues/1447)
> feat: Add SimpleUserInfo type to use in mobile client

- package-lock.json
- package.json
- src/soilId/soilIdFragments.ts
- src/soilId/soilIdService.ts
- src/soilId/soilIdSlice.ts
Updates the backend version and propogates specific soil ID failure reasons to clients.
Related to https://github.com/techmatters/terraso-product/issues/895
> feat: make more detailed soil ID failure reasons available to clients

- package-lock.json
- package.json
> build: update typescript to 5.5.3

- package-lock.json
- package.json
update @ianvs/prettier-plugin-sort-imports to 4.3.0.
> build: update @ianvs/prettier-plugin-sort-imports to 4.3.0

- package-lock.json
- package.json
update @babel/cli @babel/preset-react @babel/preset-env to 7.24.7.
> build: update @babel/cli @babel/preset-react @babel/preset-env to 7.24.7

- package-lock.json
- package.json
update @typescript-eslint/parser to 7.15.0.
> build: update @typescript-eslint/parser to 7.15.0

- package-lock.json
- package.json
update @graphql-codegen/client-preset to 4.3.2.
> build: update @graphql-codegen/client-preset to 4.3.2

- package-lock.json
- package.json
> build: update uuid to 10.0.0

- package-lock.json
- package.json
Updated backend version
- https://github.com/techmatters/terraso-web-client/issues/1941
> chore: Updated backend version

- package-lock.json
- package.json
update @babel/core@7.25.2 @babel/preset-env@7.25.3.
> build: update @babel/core@7.25.2 @babel/preset-env@7.25.3

- package-lock.json
- package.json
bump @graphql-codegen/client-preset to 4.3.3.
> build: bump @graphql-codegen/client-preset to 4.3.3

- package-lock.json
- package.json
bump @typescript-eslint/parser to 8.1.0
> build: bump @typescript-eslint/parser to 8.1.0

- package-lock.json
- package.json
- https://github.com/techmatters/terraso-product/issues/555
> chore: Upgraded backend version

- package-lock.json
- package.json
update @testing-library/jest-dom to 6.5.0.
> build: update @testing-library/jest-dom to 6.5.0

- package-lock.json
- package.json
update eslint-plugin-react to 7.35.1.
> build: update eslint-plugin-react to 7.35.1

- package-lock.json
- package.json
update eslint-plugin-react to 7.37.0
> build: update eslint-plugin-react to 7.37.0

- package-lock.json
- package.json
> Revert "build: bump uuid from 10.0.0 to 11.0.3 (#1066)"

- src/soilId/soilIdService.ts
- src/soilId/soilIdTypes.ts
Assorted refactoring / cleanup to support offline soil ID, mostly removing types and functions which are replaced in the offline support version.
#2372
Verify functionality in main pull request
> feat: offline soil

- package-lock.json
- package.json
> build: update typescript@5.7.3

- package-lock.json
- package.json
update @babel/core@7.26.7 @babel/preset-env@7.26.7 @babel/preset-react@7.26.3
> build: update @babel/core@7.26.7 @babel/preset-env@7.26.7 @babel/preset-react@7.26.3

- package-lock.json
- package.json
update @testing-library/react@16.2.0.
> build: update @testing-library/react@16.2.0

- package-lock.json
- package.json
> build: update @types/lodash@4.17.15

- package-lock.json
- package.json
install @typescript-eslint/parser@8.23.0.
> build: install @typescript-eslint/parser@8.23.0

- package-lock.json
- package.json
update @graphql-codegen/client-preset@4.6.2
> build: update @graphql-codegen/client-preset@4.6.2

- package-lock.json
- package.json
update @babel/core@7.26.8  @babel/preset-env@7.26.8.
> build: update @babel/core@7.26.8  @babel/preset-env@7.26.8

- .husky/pre-commit
- Makefile
- package-lock.json
- package.json
- scripts/pre-commit.sample
use husky for pre-commit linting
only lint changed files
> build: use husky for pre-commit linting

- package-lock.json
- package.json
> build: update uuid to 11.1.0

- package-lock.json
- package.json
> build: update lint-staged to 15.5.0

- package-lock.json
- package.json
> build: update ts-jest to 29.3.0

- package-lock.json
- package.json
> build: update prettier to 3.5.3

- package-lock.json
- package.json
> build: update husky to 9.1.7

- package-lock.json
- package.json
update eslint-plugin-prettier to 5.2.5
> build: update eslint-plugin-prettier to 5.2.5

- package-lock.json
- package.json
update @types/lodash to 4.17.16
> build: update @types/lodash to 4.17.16

- package-lock.json
- package.json
update @typescript-eslint/parser to 8.28.0
> build: update @typescript-eslint/parser to 8.28.0

- package-lock.json
- package.json
update eslint-config-prettier to 10.1.1
> build: update eslint-config-prettier to 10.1.1

- package-lock.json
- package.json
update @babel/cli@7.27.0 @babel/preset-typescript@7.27.0 @babel/preset-env@7.26.9 @babel/core@7.26.10
> build: update @babel/cli@7.27.0 @babel/preset-typescript@7.27.0 @babel/preset-env@7.26.9 @babel/core@7.26.10

- package-lock.json
- package.json
> build: update jest-axe to 10.0.0

- package-lock.json
- package.json
update @graphql-codegen/cli to 5.0.5
> build: update @graphql-codegen/cli to 5.0.5

- package.json
Bump client-shared's dependency on terraso-backend to the most recent backend commit
Required for https://github.com/techmatters/terraso-backend/issues/1618
> chore: Update terraso-backend dependency

- package-lock.json
- package.json
Revert "Use uuid 11.1.0 again" 😢 
This reverts commit c4b83627440824c996f6cae6f7d9a74a5b6ef2e2
> fix: Sigh, go back to uuid 10.0.0 because 11 was causing app crashes
